spring:
  application:
    name: Slack
  
  file.upload-dir: /uploads/resumes

  servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB

  

  profiles:
    active:
    - dev
  


